source 'https://rubygems.org'
gem 'rails', '4.2.4'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'pg', '~> 0.18.1'
gem 'bootstrap-sass'
gem 'devise'
gem 'devise_invitable'
gem 'colorize'
gem 'openssl-extensions', :require => 'openssl-extensions/all'
gem 'irbtools', require: 'irbtools/binding'
gem 'brakeman', :require => false
gem 'rails_best_practices', :require => false
gem 'rubocop', :require => false
gem 'rubycritic', :require => false
gem 'sqlite3'
gem 'zip-zip'
gem 'selenium-webdriver' #, '2.0.0'
gem 'capybara' #, '2.4.0'
gem 'byebug'
gem 'letter_opener'
gem 'database_cleaner'
gem 'factory_girl_rails'
gem 'faker'
gem 'rspec-rails'
gem 'better_errors'
gem 'capistrano', '~> 3.4.0'
gem 'capistrano-bundler'
gem 'capistrano-rails'
gem 'capistrano-passenger'
gem 'capistrano-rvm'
gem 'capistrano-composer'
gem 'capistrano-sidekiq'
gem 'capistrano-rails-console'
gem 'guard-bundler'
gem 'spork-rails' #, github: 'sporkrb/spork-rails' # rubygems version not rails 4 compatible
gem 'childprocess'
gem 'guard'
gem 'spring'
gem 'serverspec'
gem 'therubyracer', platforms: :ruby
gem 'did_you_mean'
gem 'docker-api'
gem 'rspec'
gem 'fuubar'
gem 'spork'
gem 'headless'
gem 'poltergeist'
gem 'gemsurance'
gem 'letter_opener_web', '~> 1.2.0'
gem 'newrelic_rpm'
gem 'capybara'
gem 'capybara-webkit'
gem 'capybara-screenshot'
gem 'launchy'
gem 'selenium-webdriver'
gem 'brakeman'
gem 'bullet'
gem 'benchmark-ips'
gem 'derailed'
gem 'stackprof'
gem 'guard-spork'
gem 'guard-rails'
gem 'guard-rspec'
gem 'guard-livereload'
gem 'quiet_assets'
gem 'rails_layout'
gem 'rb-fchange', :require=>false
gem 'rb-fsevent', :require=>false
gem 'rb-inotify', :require=>false
gem 'spring-commands-rspec'
gem 'method_profiler'
gem 'to_factory'
gem 'rspec_api_documentation'
gem 'spork-rails' # , github: 'sporkrb/spork-rails' # rubygems version not rails 4 compatible
